import { Inter } from "next/font/google"
import "./globals.scss"

import Header from '@/components/Header/Header'
const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Micon",
  description: "Generated by create next app",
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='wrapper'>
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
