import { Inter } from "next/font/google";
import "./styles/globals.scss";

import { dbConnect } from "@/lib/mongo";
const inter = Inter({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Lad",
  description: "Generated by create next app",
  icons: {
    icon: ['/logo.svg?v=4']
  }
};

export default async function RootLayout({ children }) {
  const conn = await dbConnect();
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
